version: '3.8'

services:
  api:
    build: .
    container_name: steel_defect_api
    ports:
      - "8000:8000"
    volumes:
      - ./checkpoints:/app/checkpoints
    environment:
      - PORT=8000
    restart: always
